services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: vasta
      POSTGRES_DB: vasta_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  vasta-api:
    build: .
    volumes:
      - //d/Vasta/vasta:/rails
    command: [ "bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0" ]
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://vasta:password@db:5432/vasta_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    user: root

  sidekiq:
    build: .
    volumes:
      - //d/Vasta/vasta:/rails
    command: [ "bundle", "exec", "sidekiq" ]
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://vasta:password@db:5432/vasta_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    user: root

volumes:
  postgres_data:
  redis_data:
