services:
  - type: web
    name: vasta-api
    env: docker
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false # Você precisará colar a URL do Neon aqui no Painel do Render
      - key: SUPABASE_JWT_SECRET
        sync: false # Colar o JWT Secret do Supabase aqui
      - key: STRIPE_SECRET_KEY
        sync: false # Chave secreta do Stripe
