name = "vasta-web"
pages_build_output_dir = "out"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "please_replace_with_your_kv_id"
